USE K_UNIVER
GO

-- 1
SELECT * FROM FACULTY;
-- 2
SELECT TEACHER, PULPIT FROM TEACHER;
-- 3
SELECT TEACHER_NAME, PULPIT FROM TEACHER WHERE PULPIT = 'ИСиТ';
-- 4
SELECT TEACHER_NAME, PULPIT FROM TEACHER WHERE PULPIT = 'ИСиТ' OR PULPIT = 'ПОиСОИ' ORDER BY PULPIT;
-- 5
SELECT TEACHER_NAME, GENDER, PULPIT FROM TEACHER WHERE PULPIT = 'ИСиТ' AND GENDER = 'ж';
-- 6
SELECT TEACHER_NAME  AS 'Имя преподавателя' FROM TEACHER WHERE GENDER != 'ж' AND PULPIT = 'ИСиТ';
-- 7
SELECT DISTINCT PULPIT FROM TEACHER;
-- 8
SELECT AUDITORIUM, AUDITORIUM_CAPACITY FROM AUDITORIUM ORDER BY AUDITORIUM_CAPACITY;
-- 9
SELECT TOP 2 AUDITORIUM_TYPE, AUDITORIUM, AUDITORIUM_CAPACITY FROM AUDITORIUM ORDER BY AUDITORIUM_CAPACITY DESC;
-- 10
SELECT SUBJECT, NOTE FROM PROGRESS WHERE NOTE >= 8 ORDER BY NOTE
-- 11
SELECT DISTINCT SUBJECT, PULPIT FROM SUBJECT WHERE PULPIT IN('ЛЗиДВ', 'ПОиСОИ', 'ОВ');
-- 12
SELECT PROFESSION_NAME AS 'Наименование специальности', QUALIFICATION AS 'Квалификация' FROM PROFESSION WHERE QUALIFICATION LIKE '%химиК%';

-- 13

drop table #TABLE1
SELECT NAME, BDAY
INTO #TABLE1
FROM STUDENT
ORDER BY BDAY;
 
SELECT #TABLE1.NAME, #TABLE1.BDAY
FROM #TABLE1



