USE K_UNIVER
GO

-- Z_1
SELECT * FROM FACULTY;

-- Z_2
SELECT TEACHER, PULPIT FROM TEACHER;

-- Z_3
SELECT TEACHER_NAME, PULPIT FROM TEACHER WHERE PULPIT = 'ИСиТ';

-- Z_4
SELECT TEACHER_NAME, PULPIT FROM TEACHER WHERE PULPIT = 'ИСиТ' OR PULPIT = 'ПОиСОИ' ORDER BY PULPIT;

-- Z_5
SELECT TEACHER_NAME, GENDER, PULPIT FROM TEACHER WHERE PULPIT = 'ИСиТ' AND GENDER = 'ж';

-- Z_6
SELECT TEACHER_NAME  AS 'Имя преподавателя' FROM TEACHER WHERE GENDER != 'ж' AND PULPIT = 'ИСиТ';

-- Z_7
SELECT DISTINCT PULPIT FROM TEACHER;

-- Z_8
SELECT AUDITORIUM, AUDITORIUM_CAPACITY FROM AUDITORIUM ORDER BY AUDITORIUM_CAPACITY;

-- Z_9
SELECT TOP 2 AUDITORIUM_TYPE, AUDITORIUM, AUDITORIUM_CAPACITY FROM AUDITORIUM ORDER BY AUDITORIUM_CAPACITY DESC;

-- Z_10
SELECT SUBJECT, NOTE FROM PROGRESS WHERE NOTE >= 8 ORDER BY NOTE;

-- Z_11
SELECT DISTINCT SUBJECT, PULPIT FROM SUBJECT WHERE PULPIT IN('ЛЗиДВ', 'ПОиСОИ', 'ОВ');

-- Z_12
SELECT PROFESSION_NAME AS 'Наименование специальности', QUALIFICATION AS 'Квалификация' FROM PROFESSION WHERE QUALIFICATION LIKE '%химиК%';

-- Z_13

SELECT NAME, BDAY
INTO #TABLE
FROM STUDENT
ORDER BY BDAY;
 
SELECT #TABLE.NAME, #TABLE.BDAY
FROM #TABLE