USE [K_UNIVER];

-- TASK 1
SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME, PROFESSION.PROFESSION_NAME
	FROM PULPIT, FACULTY, PROFESSION
	WHERE 
		PULPIT.FACULTY = FACULTY.FACULTY AND  
		FACULTY.FACULTY = PROFESSION.FACULTY AND
		PROFESSION.PROFESSION_NAME IN 
			( SELECT PROFESSION.PROFESSION_NAME FROM PROFESSION
					WHERE 
						PROFESSION.PROFESSION_NAME LIKE '%технология%' OR
						PROFESSION.PROFESSION_NAME LIKE '%технологии%' )
	ORDER BY PROFESSION.PROFESSION_NAME;

-- TASK 2
SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME, PROFESSION.PROFESSION_NAME
	FROM PULPIT 
		JOIN PROFESSION
			ON PULPIT.FACULTY = PROFESSION.FACULTY AND 
				 PROFESSION.PROFESSION_NAME IN 
					( SELECT PROFESSION.PROFESSION_NAME FROM PROFESSION
							WHERE 
								PROFESSION.PROFESSION_NAME LIKE '%технология%' OR
								PROFESSION.PROFESSION_NAME LIKE '%технологии%' )
		JOIN FACULTY
			ON PULPIT.FACULTY = FACULTY.FACULTY;

-- TASK 3
SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME, PROFESSION.PROFESSION_NAME
	FROM PULPIT 
		JOIN PROFESSION
			ON PULPIT.FACULTY = PROFESSION.FACULTY AND 
				( PROFESSION.PROFESSION_NAME LIKE '%технология%' OR
					PROFESSION.PROFESSION_NAME LIKE '%технологии%' )
		JOIN FACULTY
			ON PULPIT.FACULTY = FACULTY.FACULTY;

-- TASK 4
SELECT AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE
	FROM AUDITORIUM AS A_1
	WHERE 
		AUDITORIUM_CAPACITY = ( 
			SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM AS A_2
				WHERE A_1.AUDITORIUM_TYPE = A_2.AUDITORIUM_TYPE )
	ORDER BY AUDITORIUM_CAPACITY DESC;

-- TASK 5
SELECT FACULTY.FACULTY_NAME FROM FACULTY
	WHERE EXISTS 
		( SELECT * FROM PULPIT
				WHERE PULPIT.FACULTY = FACULTY.FACULTY );

-- TASK 6 
SELECT TOP( 1 )
	( SELECT AVG( PROGRESS.NOTE ) FROM PROGRESS
			WHERE PROGRESS.SUBJECT = 'ОАиП' ) AS OOP,
	( SELECT AVG( PROGRESS.NOTE ) FROM PROGRESS
			WHERE PROGRESS.SUBJECT = 'БД' ) AS DB,
	( SELECT AVG( PROGRESS.NOTE ) FROM PROGRESS
			WHERE PROGRESS.SUBJECT = 'СУБД' ) AS DBMS
	FROM PROGRESS;

-- TASK 7 
SELECT * FROM AUDITORIUM
	WHERE AUDITORIUM_CAPACITY < ALL( SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM
		WHERE AUDITORIUM_TYPE = 'ЛК' )
	ORDER BY AUDITORIUM_TYPE;

SELECT * FROM AUDITORIUM ORDER BY AUDITORIUM_TYPE, AUDITORIUM_CAPACITY

--  TASK 8 
SELECT * FROM AUDITORIUM
	WHERE AUDITORIUM_CAPACITY < ANY( SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM
		WHERE AUDITORIUM_TYPE = 'ЛК' )
	ORDER BY AUDITORIUM_TYPE;




USE H_MyBase
--Найти заказы которые выполнялись в один день
select * from Заказы AS T_1 where Дата_продажи IN (select Дата_продажи from Заказы as Т_2 where T_1.Дата_продажи= Т_2.Дата_продажи and T_1.ID_Заказа <> Т_2.ID_Заказа)


--Найти клиентов которые покупали товары со скидками
select Заказы.ID_Клиента, Заказы.ID_Скидки  from Заказы 
	join ( select * from Клиент ) as t2
		on t2.ID_Клиента = Заказы.ID_Клиента


