USE K_UNIVER;

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM INNER	JOIN AUDITORIUM_TYPE
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
		AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%';

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM, AUDITORIUM_TYPE
	WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM, AUDITORIUM_TYPE
	WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
		AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%';


SELECT FACULTY.FACULTY_NAME AS 'Факультет',
			 PULPIT.PULPIT_NAME AS 'Кафедра',
			 GROUPS.PROFESSION AS 'Специальность',
			 SUBJECT.SUBJECT_NAME AS 'Дисциплина',
			 STUDENT.IDSTUDENT AS '№',
			 STUDENT.NAME AS 'Имя студента',
	CASE 
		WHEN PROGRESS.NOTE = 6 THEN 'шесть'
		WHEN PROGRESS.NOTE = 7 THEN 'семь'
		WHEN PROGRESS.NOTE = 8 THEN 'восемь'
	END 'Оценка'
	FROM GROUPS
		JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION
		JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
		JOIN SUBJECT ON SUBJECT.PULPIT = PULPIT.PULPIT
		JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT AND PROGRESS.NOTE BETWEEN 6 AND 8
		ORDER BY FACULTY.FACULTY, PULPIT.PULPIT, PROFESSION.PROFESSION, STUDENT.NAME ASC, PROGRESS.NOTE DESC
		

SELECT FACULTY.FACULTY_NAME AS 'Факультет',
			 PULPIT.PULPIT_NAME AS 'Кафедра',
			 GROUPS.PROFESSION AS 'Специальность',
			 SUBJECT.SUBJECT_NAME AS 'Дисциплина',
			 STUDENT.IDSTUDENT AS '№',
			 STUDENT.NAME AS 'Имя студента',
	CASE 
		WHEN PROGRESS.NOTE = 6 THEN 'шесть'
		WHEN PROGRESS.NOTE = 7 THEN 'семь'
		WHEN PROGRESS.NOTE = 8 THEN 'восемь'
	END 'Оценка'
	FROM GROUPS
		JOIN STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
		JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
		JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION
		JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
		JOIN SUBJECT ON SUBJECT.PULPIT = PULPIT.PULPIT
		JOIN PROGRESS ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT AND PROGRESS.NOTE BETWEEN 6 AND 8
		ORDER BY ( 
			CASE PROGRESS.NOTE
				WHEN 7 THEN 3
				WHEN 8 THEN 2
				ELSE 1
			END 
		 ) DESC
		
SELECT PULPIT.PULPIT_NAME AS 'Кафедра',
			 ISNULL( TEACHER.TEACHER_NAME, '***' ) AS 'Преподаватель'
	FROM PULPIT LEFT JOIN TEACHER 
		ON PULPIT.PULPIT = TEACHER.PULPIT

SELECT PULPIT.PULPIT_NAME AS 'Кафедра',
			 ISNULL( TEACHER.TEACHER_NAME, '***' ) AS 'Преподаватель'
	FROM TEACHER RIGHT JOIN PULPIT
		ON PULPIT.PULPIT = TEACHER.PULPIT

SELECT * FROM AUDITORIUM_TYPE FULL OUTER JOIN AUDITORIUM
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	ORDER BY AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT * FROM AUDITORIUM_TYPE FULL OUTER JOIN AUDITORIUM
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	WHERE AUDITORIUM IS NULL

SELECT  AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	FROM AUDITORIUM_TYPE CROSS JOIN AUDITORIUM
		WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;